name: Node.js CI

on:
  push:
  schedule:
    - cron: '0 2 * * 1-5'

jobs:
 tests:
    runs-on: ubuntu-latest

    steps:
      #Checkout kodu z repo
    - uses: actions/checkout@v4
      #wersja Node.js
    - name: Use Node.js 20
      #instalacja zależności
      uses: actions/setup-node@v4
      with:
        node-version: 20
      #wykonujemy testy
    - run: npm install
    - run: npm test



